services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/logs:/logs/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_US
      - UI_APPNAME=Stirling PDF
      - UI_HOMEDESCRIPTION= Your locally hosted PDF Editing Service
      - UI_APPNAVBARNAME=Stirling PDF
    networks:
      - caddy_net 
    restart: unless-stopped

networks:
  caddy_net:
    external: true